// Inspired by iso-language-codes.
// See https://github.com/pubcore/iso-language-codes/blob/master/src/data.ts
export const langMap: Record<string, string> = {
  sr: "српски језик",
  ro: "Română",
  ii: "ꆈꌠ꒿ Nuosuhxop",
  ty: "Reo Tahiti",
  tl: "Wikang Tagalog",
  yi: "ייִדיש",
  ak: "Akan",
  ms: "Bahasa Melayu, بهاس ملايو",
  ar: "العربية",
  no: "Norsk",
  oj: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  ff: "Fulfulde, Pulaar, Pular",
  fa: "فارسی",
  sq: "Shqip",
  ay: "aymar aru",
  az: "azərbaycan dili",
  zh: "中文 (Zhōngwén), 汉语, 漢語",
  cr: "ᓀᐦᐃᔭᐍᐏᐣ",
  et: "eesti, eesti keel",
  gn: "Avañe'ẽ",
  ik: "Iñupiaq, Iñupiatun",
  iu: "ᐃᓄᒃᑎᑐᑦ",
  kr: "Kanuri",
  kv: "коми кыв",
  kg: "Kikongo",
  ku: "Kurdî, أۇزبېك",
  lv: "latviešu valoda",
  mg: "fiteny malagasy",
  mn: "Монгол хэл",
  om: "Afaan Oromoo",
  ps: "پښتو",
  qu: "Runa Simi, Kichwa",
  sc: "sardu",
  sw: "Kiswahili",
  uz: "Oʻzbek, Ўзбек, ",
  za: "Saɯ cueŋƅ, Saw cuengh",
  bi: "Bislama",
  nb: "Norsk Bokmål",
  nn: "Norsk Nynorsk",
  id: "Bahasa Indonesia",
  tw: "Twi",
  eo: "Esperanto",
  ia: "Interlingua",
  ie: "Originally called Occidental; then Interlingue after WWII",
  io: "Ido",
  vo: "Volapük",
  bh: "भोजपुरी",
  he: "עברית",
  sa: "संस्कृतम्",
  cu: "ѩзыкъ словѣньскъ",
  pi: "पाऴि",
  ae: "avesta",
  la: "latine, lingua latina",
  hy: "Հայերեն",
  ss: "SiSwati",
  bo: "བོད་ཡིག",
  nr: "isiNdebele",
  sl: "Slovenski Jezik, Slovenščina",
  or: "ଓଡ଼ିଆ",
  nd: "isiNdebele",
  na: "Dorerin Naoero",
  mi: "te reo Māori",
  mr: "मराठी",
  lu: "Kiluba",
  rn: "Ikirundi",
  km: "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ",
  fy: "Frysk",
  bn: "বাংলা",
  av: "авар мацӀ, магӀарул мацӀ",
  ab: "аҧсуа бызшәа, аҧсшәа",
  aa: "Afaraf",
  af: "Afrikaans",
  am: "አማርኛ",
  an: "aragonés",
  as: "অসমীয়া",
  bm: "bamanankan",
  ba: "башҡорт теле",
  eu: "euskara, euskera",
  be: "беларуская мова",
  bs: "bosanski jezik",
  br: "brezhoneg",
  bg: "български език",
  my: "ဗမာစာ",
  ca: "català, valencià",
  ch: "Chamoru",
  ce: "нохчийн мотт",
  ny: "chiCheŵa, chinyanja",
  cv: "чӑваш чӗлхи",
  kw: "Kernewek",
  co: "corsu, lingua corsa",
  hr: "hrvatski jezik",
  cs: "čeština, český jazyk",
  da: "dansk",
  dv: "ދިވެހި",
  nl: "Nederlands, Vlaams",
  dz: "རྫོང་ཁ",
  en: "English",
  ee: "Eʋegbe",
  fo: "føroyskt",
  fj: "vosa Vakaviti",
  fi: "suomi, suomen kieli",
  fr: "français, langue française",
  gl: "Galego",
  ka: "ქართული",
  de: "Deutsch",
  el: "ελληνικά",
  gu: "ગુજરાતી",
  ht: "Kreyòl ayisyen",
  ha: "(Hausa) هَوُسَ",
  hz: "Otjiherero",
  hi: "हिन्दी, हिंदी",
  ho: "Hiri Motu",
  hu: "magyar",
  ga: "Gaeilge",
  ig: "Asụsụ Igbo",
  is: "Íslenska",
  it: "Italiano",
  ja: "日本語 (にほんご)",
  jv: "ꦧꦱꦗꦮ, Basa Jawa",
  kl: "kalaallisut, kalaallit oqaasii",
  kn: "ಕನ್ನಡ",
  ks: "कश्मीरी, كشميري",
  kk: "қазақ тілі",
  ki: "Gĩkũyũ",
  rw: "Ikinyarwanda",
  ky: "Кыргызча, Кыргыз тили",
  ko: "한국어",
  kj: "Kuanyama",
  lb: "Lëtzebuergesch",
  lg: "Luganda",
  li: "Limburgs",
  ln: "Lingála",
  lo: "ພາສາລາວ",
  lt: "lietuvių kalba",
  gv: "Gaelg, Gailck",
  mk: "македонски јазик",
  ml: "മലയാളം",
  mt: "Malti",
  mh: "Kajin M̧ajeļ",
  nv: "Diné bizaad",
  ne: "नेपाली",
  ng: "Owambo",
  oc: "occitan, lenga d'òc",
  os: "ирон æвзаг",
  pa: "ਪੰਜਾਬੀ",
  pl: "język polski, polszczyzna",
  pt: "Português",
  rm: "Rumantsch Grischun",
  ru: "русский",
  sd: "सिन्धी, سنڌي، سندھی",
  se: "Davvisámegiella",
  sm: "gagana fa'a Samoa",
  sg: "yângâ tî sängö",
  gd: "Gàidhlig",
  sn: "chiShona",
  si: "සිංහල",
  sk: "Slovenčina, Slovenský Jazyk",
  so: "Soomaaliga, af Soomaali",
  st: "Sesotho",
  es: "Español",
  su: "Basa Sunda",
  sv: "Svenska",
  ta: "தமிழ்",
  te: "తెలుగు",
  tg: "тоҷикӣ, toçikī, تاجیکی",
  th: "ไทย",
  ti: "ትግርኛ",
  tk: "Türkmen, Түркмен",
  tn: "Setswana",
  to: "Faka Tonga",
  tr: "Türkçe",
  ts: "Xitsonga",
  tt: "татар теле, tatar tele",
  ug: "ئۇيغۇرچە, Uyghurche",
  uk: "Українська",
  ur: "اردو",
  ve: "Tshivenḓa",
  vi: "Tiếng Việt",
  wa: "Walon",
  cy: "Cymraeg",
  wo: "Wollof",
  xh: "isiXhosa",
  yo: "Yorùbá",
  zu: "isiZulu",
};
