set -e
prettier --check "packages/api/src/**/*.ts"
echo "✅ prettier(api)"
prettier --check "packages/artisan/src/**/*.ts"
echo "✅ prettier(artisan)"
prettier --check "packages/player/src/**/*.ts"
echo "✅ prettier(player)"
prettier --check "packages/shared/src/**/*.ts"
echo "✅ prettier(shared)"
prettier --check "packages/dashboard/src/**/*.ts" "packages/dashboard/src/**/*.tsx"
echo "✅ prettier(dashboard)"
prettier --check "packages/stitcher/src/**/*.ts"
echo "✅ prettier(stitcher)"